<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'System List',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'Other',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '4',
    'aricle_num' => '4',
  ),
  2 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'Blog',
    'cat_type' => '1',
    'keywords' => 'kbl blog',
    'cat_desc' => 'We have implemented a strict and complete quality control system, which ensures that each product can meet quality requirements of customers.',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'YSF',
    'cat_type' => '1',
    'keywords' => '公司概况',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  4 => 
  array (
    'cat_id' => '16',
    'cat_name' => 'advantage',
    'cat_type' => '1',
    'keywords' => 'advantage',
    'cat_desc' => 'advantage',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'Shop Message',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  6 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'Help2',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  7 => 
  array (
    'cat_id' => '15',
    'cat_name' => 'Human Hair News',
    'cat_type' => '1',
    'keywords' => 'Human Hair News',
    'cat_desc' => 'KBL company has been regarded as providing with the finest 100% virgin hair extensions to customer on the market.',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '4',
    'has_children' => '0',
    'aricle_num' => '288',
  ),
  8 => 
  array (
    'cat_id' => '14',
    'cat_name' => 'KBL News',
    'cat_type' => '1',
    'keywords' => 'KBL News',
    'cat_desc' => 'Located in Guangzhou, Guangzhou Kabeilu Trading Co., Ltd. is a professional manufacturer of Human Hair. ',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '4',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  9 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'Help',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '5',
  ),
);
?>