<?php
$data = array (
  0 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'Brazilian Blue Band Hair',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'Indian Hair',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '1',
    'cat_name' => 'Peruvian Hair',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'Malaysian Hair',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '38',
    'cat_name' => '7A Brazilian Hair',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'Mink Hair',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '64',
    'cat_name' => '613 Blonde Hair',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '66',
    'cat_name' => 'Clip-Ins',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '71',
    'cat_name' => 'Closure',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '9',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '44',
    'cat_name' => 'Bundles + Closure',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '78',
    'cat_name' => 'Wig',
    'measure_unit' => '50',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '74',
    'cat_name' => 'Frontal',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '27',
    'cat_name' => 'All Category',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  14 => 
  array (
    'cat_id' => '13',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  15 => 
  array (
    'cat_id' => '14',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  16 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  17 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  18 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'Kinky Curly',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  19 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  20 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  21 => 
  array (
    'cat_id' => '54',
    'cat_name' => 'Loose Curly',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  22 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  23 => 
  array (
    'cat_id' => '34',
    'cat_name' => 'Funmi hair',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'Curly',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  25 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  26 => 
  array (
    'cat_id' => '16',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  27 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  28 => 
  array (
    'cat_id' => '15',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  29 => 
  array (
    'cat_id' => '19',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  30 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  31 => 
  array (
    'cat_id' => '18',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  32 => 
  array (
    'cat_id' => '31',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 27,
  ),
  33 => 
  array (
    'cat_id' => '28',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 27,
  ),
  34 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'Funmi Hair',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 25,
  ),
  36 => 
  array (
    'cat_id' => '30',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 25,
  ),
  37 => 
  array (
    'cat_id' => '82',
    'cat_name' => 'XR',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 8,
  ),
  38 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'Curly',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'Hair Sample',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  43 => 
  array (
    'cat_id' => '39',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  44 => 
  array (
    'cat_id' => '47',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  45 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'Loose Curly',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'Curly',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  47 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  48 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  49 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  50 => 
  array (
    'cat_id' => '62',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  51 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  52 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  53 => 
  array (
    'cat_id' => '61',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  54 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '64',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  55 => 
  array (
    'cat_id' => '70',
    'cat_name' => 'Deep Wave',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'Straight',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  57 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'Body Wave',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  58 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'Loose Wave',
    'measure_unit' => '',
    'parent_id' => '66',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '83',
    'cat_name' => '5*5 Lace Closure',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '0',
    'goods_num' => 8,
  ),
  60 => 
  array (
    'cat_id' => '73',
    'cat_name' => '4*4 Silk Base Closure',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  61 => 
  array (
    'cat_id' => '72',
    'cat_name' => '4*4 Lace Closure',
    'measure_unit' => '',
    'parent_id' => '71',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  62 => 
  array (
    'cat_id' => '75',
    'cat_name' => '13*5 Lace Frontal',
    'measure_unit' => '',
    'parent_id' => '74',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  63 => 
  array (
    'cat_id' => '76',
    'cat_name' => '360 Lace Frontal',
    'measure_unit' => '',
    'parent_id' => '74',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  64 => 
  array (
    'cat_id' => '84',
    'cat_name' => '150 Transparent Frontal Wig',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '79',
    'cat_name' => '150 Density Lace Front Wig',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  66 => 
  array (
    'cat_id' => '85',
    'cat_name' => '613 Blonde Frontal Wig',
    'measure_unit' => '30',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  67 => 
  array (
    'cat_id' => '80',
    'cat_name' => '180 Density Silk Base Front Wig',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  68 => 
  array (
    'cat_id' => '81',
    'cat_name' => '180 Full Lace Wig',
    'measure_unit' => '',
    'parent_id' => '78',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '2',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
);
?>